source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "minimal-mistakes-jekyll", "~> 4.24"
gem "jekyll-feed"
gem "jekyll-gist"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-remote-theme"
gem "jekyll-sitemap"
gem "webrick"
